/**
 * api.openbed.ng -- the Worker as deployed. The decision it makes lives in
 * ./handler.ts; this file binds it to the production origin, the tracked allow-list
 * and the build stamp. See the 2026-09-19 addendum in
 * the decision record (held outside this repository) for why this domain
 * exists, and R-2026-09-23-70 for what it forwards.
 *
 * SINCE PR 3.3 IT FORWARDS ONLY WHAT THE APPS CALL (./allow-list.json). Until then it
 * forwarded every path and method. Everything else gets the Worker's own 404, marked
 * `x-openbed-proxy: refused`, and never reaches Supabase.
 *
 * THE STAMP IS WRITTEN AT DEPLOY TIME. ./version.json is gitignored and generated by
 * scripts/deploy_worker.sh from scripts/stamp_build.mjs, so a build without the
 * wrapper has no stamp to import and fails -- which is the point: the deployed
 * Worker names the commit it was built from at /__openbed/version.
 *
 * SINCE R-2026-09-30-177 (W3) it also refuses an `Upgrade` request, counts sign-in,
 * link and refresh requests per client address through the rate-limit bindings in
 * wrangler.json, and forwards GET /auth/v1/verify -- the emailed sign-in link now opens
 * on api.openbed.ng (R-2026-09-22-55 C, option T1).
 *
 * NOT AN AUTH BOUNDARY. A forwarded request is authorised exactly as it would be
 * calling the Supabase origin directly, with whatever credentials the caller presented.
 */
import { makeHandler } from './handler.ts';
import LIST from './allow-list.json';
import STAMP from './version.json';

const SUPABASE_PROJECT_ID = "klrlpxysjsjpdkeqdhvl";
const SUPABASE_ORIGIN = `https://${SUPABASE_PROJECT_ID}.supabase.co`;

const handle = makeHandler({ origin: SUPABASE_ORIGIN, list: LIST, stamp: STAMP });

export default {
  // `env` carries the rate-limit bindings (wrangler.json `ratelimits`). Dropping it
  // would silently turn every limit off, because a missing binding forwards; the
  // stamp's `limits_bound` is where that would show.
  fetch(request, env) {
    return handle(request, env);
  },
};
